//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest_in_room
    {
        public guest_in_room()
        {
            this.transactions = new HashSet<transaction>();
        }
    
        public int idguest_in_room { get; set; }
        public int guest_idguest { get; set; }
        public int room_idroom { get; set; }
        public System.DateTimeOffset date_from { get; set; }
        public Nullable<System.DateTimeOffset> date_to { get; set; }
    
        public virtual guest guest { get; set; }
        public virtual room room { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
