//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest_get_equipment
    {
        public guest_get_equipment()
        {
            this.transaction = new HashSet<transaction>();
        }
    
        public int idguest_get_equipment { get; set; }
        public int optional_equipment_idoptional_equipment { get; set; }
        public int guest_idguest { get; set; }
        public System.DateTimeOffset date_from { get; set; }
        public Nullable<System.DateTimeOffset> date_to { get; set; }
    
        public virtual guest guest { get; set; }
        public virtual optional_equipment optional_equipment { get; set; }
        public virtual ICollection<transaction> transaction { get; set; }
    }
}
