//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest
    {
        public guest()
        {
            this.guest_get_equipment = new HashSet<guest_get_equipment>();
            this.guest_in_room = new HashSet<guest_in_room>();
        }
    
        public int idguest { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string guest_comment { get; set; }
    
        public virtual ICollection<guest_get_equipment> guest_get_equipment { get; set; }
        public virtual ICollection<guest_in_room> guest_in_room { get; set; }
    }
}
