//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHostel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hostelEntities : DbContext
    {
        public hostelEntities()
            : base("name=hostelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<equipment> equipments { get; set; }
        public DbSet<guest> guests { get; set; }
        public DbSet<guest_get_equipment> guest_get_equipment { get; set; }
        public DbSet<guest_in_room> guest_in_room { get; set; }
        public DbSet<optional_equipment> optional_equipment { get; set; }
        public DbSet<room> rooms { get; set; }
        public DbSet<room_photo> room_photo { get; set; }
        public DbSet<room_type> room_type { get; set; }
        public DbSet<transaction> transactions { get; set; }
    }
}
