//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class optional_equipment
    {
        public optional_equipment()
        {
            this.guest_get_equipment = new HashSet<guest_get_equipment>();
        }
    
        public int idoptional_equipment { get; set; }
        public string name { get; set; }
        public string optional_equipment_comment { get; set; }
    
        public virtual ICollection<guest_get_equipment> guest_get_equipment { get; set; }
    }
}
