//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_photo
    {
        public int idroom_photo { get; set; }
        public int room_idroom { get; set; }
        public string url { get; set; }
        public string name { get; set; }
    
        public virtual room room { get; set; }
    }
}
