//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_type
    {
        public room_type()
        {
            this.room = new HashSet<room>();
        }
    
        public int idroom_type { get; set; }
        public Nullable<int> count_single_bed { get; set; }
        public Nullable<int> count_double_bed { get; set; }
        public Nullable<int> count_room { get; set; }
        public Nullable<bool> kitchen { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<room> room { get; set; }
    }
}
