//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int idtransaction { get; set; }
        public int guest_get_equipment_idguest_get_equipment { get; set; }
        public int guest_in_room_idguest_in_room { get; set; }
        public Nullable<int> date { get; set; }
        public Nullable<double> sum { get; set; }
    
        public virtual guest_get_equipment guest_get_equipment { get; set; }
        public virtual guest_in_room guest_in_room { get; set; }
    }
}
